### ISSUE TITLE
mostSimpleTimeTracker: issue with loading past setup

### ISSUE THREAD

**Issue by marcelpetrick** [marcelpetrick/codingWithGPT#10]
Most likely the `:` in the  string prevented loading from the ini-file. Parse and sanitize the input differently.

---

```bash
    ~/repos/codingWithGPT/mostSimpleTimeTracker    master *6 +2  python mostSimpeTimeTracker.py                                                                                                        ✔ 
Traceback (most recent call last):
  File "/home/mpetrick/repos/codingWithGPT/mostSimpleTimeTracker/mostSimpeTimeTracker.py", line 199, in <module>
    window = TimeTrackingApp()
             ^^^^^^^^^^^^^^^^^
  File "/home/mpetrick/repos/codingWithGPT/mostSimpleTimeTracker/mostSimpeTimeTracker.py", line 89, in __init__
    self.load_configuration()
  File "/home/mpetrick/repos/codingWithGPT/mostSimpleTimeTracker/mostSimpeTimeTracker.py", line 163, in load_configuration
    config.read("config.ini")
  File "/usr/lib/python3.12/configparser.py", line 684, in read
    self._read(fp, filename)
  File "/usr/lib/python3.12/configparser.py", line 1075, in _read
    raise DuplicateOptionError(sectname, optname,
configparser.DuplicateOptionError: While reading from 'config.ini' [line  3]: option 'p118' in section 'items' already exists
    ~/repos/codingWithGPT/mostSimpleTimeTracker    master *6 +2  
```

**Comment by marcelpetrick** [comment]
Implemented and pushed in [`add612c`](https://github.com/marcelpetrick/codingWithGPT/commit/add612c).

The fix configures `ConfigParser` to use only `=` as the delimiter and preserves task-name casing, so multiple entries such as `P118: Customer Alpha` and `P118: Customer Beta` load without `DuplicateOptionError`. It also pins PyQt5 to 5.15.11, removes the unnecessary `configparser` backport dependency, and documents configuration persistence.

Verified with a clean dependency installation, an exact regression reproduction, a save/load round trip, Python compilation, and `pip check`.
